name: Build Docker Image

on:
  push:
    paths:
      - 'src/frontend/**'
      - 'src/cartservice/**'
      - 'src/checkoutservice/**'
      - 'src/currencyservice/**'
      - 'src/emailservice/**'
      - 'src/adservice/**'
      - 'src/loadgenerator/**'
      - 'src/paymentservice/**'
      - 'src/productcatalogservice/**'
      - 'src/recommendservice/**'
      - 'src/shippingservice/**'
      - 'src/shoppingassistantservice/**'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.set-matrix.outputs.services }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Detect Changed Microservices
        id: set-matrix
        run: |
          echo "Changed files:"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}

          changed=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "Changed files: $changed"

          services=()
          for dir in src/frontend src/cartservice src/checkoutservice src/currencyservice src/emailservice src/adservice src/loadgenerator src/paymentservice src/productcatalogservice src/recommendservice src/shippingservice src/shoppingassistantservice; do
            if echo "$changed" | grep -q "^$dir/"; then
              services+=("{\"service\":\"$dir\"}")
            fi
          done

          echo "Detected services: ${services[*]}"

          matrix="{\"include\":["
          if [ ${#services[@]} -gt 0 ]; then
            matrix+=$(IFS=, ; echo "${services[*]}")
          fi
          matrix+="]}"
          echo "Matrix: $matrix"
          echo "services=$matrix" >> $GITHUB_OUTPUT
  build-and-push:
    needs: detect-changes
    if: needs.detect-changes.outputs.services != '{"include":[]}'
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.detect-changes.outputs.services) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.service }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.service }}-

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.CICD_DOCKERHUB }}

      - name: Build and Push Docker Image
        env:
          SERVICE: ${{ matrix.service }}
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        run: |
          echo "Building and pushing service: $SERVICE"
          NAME=$(basename $SERVICE)
          IMAGE_LATEST=$DOCKER_USER/$NAME:latest
          IMAGE_SHA=$DOCKER_USER/$NAME:${GITHUB_SHA::7}

          docker buildx build \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache-new \
            --push \
            -t $IMAGE_LATEST \
            -t $IMAGE_SHA \
            $SERVICE
